### ISSUE TITLE
Outdated GitHub and documentation URLs

### ISSUE THREAD

**Issue by joaopalmeiro** [FelixRilling/lightdash#40]
Hi! 👋 

If I'm correct, the GitHub URL (`package.json`) should be updated from `https://github.com/FelixRilling/lightdash` to `https://github.com/RillingDev/lightdash`, as well as the documentation website one (`README.md` and repo) from `https://felixrilling.github.io/lightdash/` to `https://rillingdev.github.io/lightdash/`. 

Let me know if I can help in any way.

**Comment by RillingDev** [comment]
Hi! Thanks for the heads up, should be fixed now :)

**Comment by joaopalmeiro** [comment]
Nice, thanks!

Btw, the repo URL is still outdated:

![image](https://github.com/RillingDev/lightdash/assets/17132927/71510063-c7e5-452e-a2fc-d8bcbaff158c)

**Comment by RillingDev** [comment]
Oops, I missed that too. Thanks!
